### ISSUE TITLE
Leaderboard: latest contribution not working

### ISSUE THREAD

**Issue by okin** [cssfrankfurt/hacktoberfest2018#34]
After signing up for the leaderboard I noticed that my latest contribution wasn't the latest contribution I made but it is the first one I made during hacktoberfest.
I'd expect it to be one of the latest (iirc this should currently be mozilla-services/syncserver) but it is showing an old one (to stdevel/katprep).

**Comment by flxwu** [comment]
it shows the latest project you opened a PR to :)

**Comment by flxwu** [comment]
Hey @okin , after checking again, I did indeed make a mistake on the backend side, so thanks a lot for noting this! It should be fixed now, please comment below if the data is still outdated! :)

**Comment by okin** [comment]
@flxwu looks fine to me now :)
