### ISSUE TITLE
Leaderbord showing Not Found directly

### ISSUE THREAD

**Issue by okin** [cssfrankfurt/hacktoberfest2018#35]
If you open https://hacktoberfestffm.de/leaderboard directly it will show an error along with the message _Not Found_.

Since this is the URL a user gets redirected to after registering I'd expect this page to show the leaderboard instead of an error page.
Reloading this page unfortunately does not lead to the leaderboard appearing which my lead to people believe the site is broken.

**Comment by flxwu** [comment]
thanks, should be fixed :)
