### ISSUE TITLE
Too broad GitHub permissions

### ISSUE THREAD

**Issue by fleaz** [cssfrankfurt/hacktoberfest2018#44]
Hi,

when registering for the leaderbaord the app asks for Read/Write permissions on "commit statuses" (See attached screenshot).
This is probably a configuration issue, because the leaderboard obviously doesn't need to modify anything and just reads a list of PRs, does it?

Best regards,
Felix

<img width="502" alt="screenshot 2018-10-12 at 14 42 04" src="https://user-images.githubusercontent.com/2489598/46869756-11115980-ce2d-11e8-9763-37777fbd7ee8.png">

**Comment by flxwu** [comment]
Hey @fleaz !

Thanks for reaching out! Yeah, you're right. We initially wanted to include private repos as well but since only public PRs count towards Hacktoberfest, we should remove the scope. Thanks for opening this issue! 🙂

**Comment by flxwu** [comment]
Should be fixed in #45
